{{- if .Values.certificate.enabled -}}
{{- $fullName := include "backend.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-certificate
spec:
  secretName: {{ $fullName }}-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.certificate.serviceName }}
{{- end }}
